#!/bin/sh
# Regenerates the two build artifacts:
#   persona5.css  = tokens.css + components.css, the file npm and CDN users load
#   index.html    = the styleguide, with every stylesheet inlined
# Run after editing tokens.css, components.css, page-shell.css or page-body.html.
set -e
cd "$(dirname "$0")"

{
  cat <<'BANNER'
/* Persona 5 Design System — tokens + components in one file.
   Generated by build.sh. Edit tokens.css / components.css, not this. */
BANNER
  cat tokens.css components.css
} > persona5.css
echo "built persona5.css ($(wc -c < persona5.css | tr -d ' ') bytes)"

{
  cat <<'HEAD'
<title>Persona 5 Design System</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Anton&family=Archivo:wght@400;600;700&family=Rock+Salt&display=swap">
<style>
HEAD
  cat tokens.css components.css page-shell.css
  echo '</style>'
  cat page-body.html
} > index.html
echo "built index.html ($(wc -c < index.html | tr -d ' ') bytes)"
